# Generated by Django 4.2.7 on 2024-04-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, default='salicicola', max_length=100, null=True)),
                ('component', models.CharField(blank=True, default='default', max_length=100, null=True)),
                ('version', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('reporter', models.CharField(blank=True, default='AZ', max_length=100, null=True, verbose_name='user name')),
                ('actual_user', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='submitted by')),
                ('severity', models.CharField(blank=True, default='medium', max_length=100, null=True)),
                ('priority', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('hardware', models.CharField(blank=True, default='server', max_length=100, null=True)),
                ('OS', models.CharField(blank=True, default='linux', max_length=100, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='committed', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lcid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('long_name', models.CharField(blank=True, max_length=100, null=True)),
                ('public_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(default='Massachusetts', max_length=100)),
                ('state_abbr', models.CharField(default='MA', max_length=2)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('modified', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('locID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(default='Massachusetts', max_length=100)),
                ('state_abbr', models.CharField(default='MA', max_length=2)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('modified', models.DateTimeField(null=True)),
            ],
        ),
    ]
