# Generated by Django 3.1 on 2024-04-19 20:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField(default=0, help_text='Area of Country in SQ meters')),
                ('lcid', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('subregion', models.CharField(max_length=50)),
                ('lon', models.FloatField(help_text='Longitude of centerpoint', verbose_name='Longitude')),
                ('lat', models.FloatField(help_text='Latitude of centerpoint', verbose_name='Latitude')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Country Border')),
            ],
            options={
                'verbose_name_plural': 'Localities',
            },
        ),
        migrations.CreateModel(
            name='MACounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('fips_id', models.IntegerField()),
                ('state', models.CharField(default='MA', max_length=2)),
                ('county', models.CharField(max_length=15)),
                ('lcid', models.CharField(blank=True, default='', max_length=21, null=True)),
                ('area_acres', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('shape_len', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'MA Counties',
            },
        ),
        migrations.CreateModel(
            name='Openspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=120, null=True)),
                ('lcid', models.CharField(blank=True, max_length=120, null=True)),
                ('lcid_name', models.CharField(blank=True, max_length=120, null=True)),
                ('fee_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_abrv', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_type', models.CharField(blank=True, max_length=1, null=True)),
                ('manager', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_access', models.CharField(blank=True, max_length=1, null=True)),
                ('oli_1_org', models.CharField(blank=True, max_length=100, null=True)),
                ('oli_1_abrv', models.CharField(blank=True, max_length=20, null=True)),
                ('gis_acres', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
                ('shape_len', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Openspace',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(blank=True, max_length=21, null=True)),
                ('state', models.CharField(blank=True, default='MA', max_length=21, null=True)),
                ('county', models.CharField(blank=True, default='', max_length=21, null=True)),
                ('lcid', models.CharField(blank=True, default='', max_length=21, null=True)),
                ('type', models.CharField(blank=True, max_length=2, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('shape_len', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'MA Towns',
            },
        ),
        migrations.CreateModel(
            name='USCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('state_name', models.CharField(max_length=25)),
                ('state_fips', models.CharField(max_length=2)),
                ('cnty_fips', models.CharField(max_length=3)),
                ('fips', models.CharField(max_length=5)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'US Counties',
            },
        ),
    ]
