"""
Django settings for django4 project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sde-dfns%9dx7cw#=rm9w8c1yunr5pu8e5h^%pmd79_r1h+-gb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','192.168.1.9',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
'django.contrib.humanize',

'names',
'common',
##'bugs',
'photodb',
##'survey',
##'townmapper5',
##'herbarium',

##'checklist',  ## and next without models/tables by itself
'gallery',
'photos',
##'inaturalist', ## copied from linode version
##
'django.contrib.gis',
'gisapp',
##'journal', 
##'flora',
##'LC',
##'deane96', ## cannot import name 'PlantName' from 'flora.models' > copied to deane96
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django4.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {},
    "auth_db": {
        "NAME": BASE_DIR / 'data/auth_db.sqlite3',
        'ENGINE': 'django.db.backends.sqlite3',
     },
    "data_db": {
        "NAME": BASE_DIR / 'data/data_db.sqlite3',
        'ENGINE': 'django.db.backends.sqlite3',
    },
    "gisapp": {
        "NAME": BASE_DIR / 'data/gisapp_db.sqlite3',
        'ENGINE': 'django.contrib.gis.db.backends.spatialite',
    },
}

##DATABASE_ROUTERS = ["django4.AuthRouter.AuthRouter", "django4.DataRouter.DataRouter", "django4.GisRouter.GisRouter",]
DATABASE_ROUTERS = ["django4.AuthRouter.AuthRouter", "django4.PrimaryRouter.PrimaryRouter", "django4.GisRouter.GisRouter",]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
STATICFILES_DIRS =  (os.path.join(BASE_DIR, 'data/static'),)

CACHES = {
   'default': {
      'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
       ##'LOCATION': '/var/tmp/django_cache',
          'LOCATION': os.path.join(BASE_DIR, "CACHE")
   }
}

MEDIA_ROOT = BASE_DIR
